---
  - name: restart celeryd
    service:
        name: celeryd
        state: restarted

  - name: restart celerybeat
    service:
        name: celerybeat
        state: restarted

  - name: restart rabbitmq
    service:
        name: rabbitmq-server
        state: restarted
