---
- name: Install necessary OS packages
  yum:
      name: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
      - libselinux-python

- name: Creates destination directory
  file:
      dest: "/root/.ssh/"
      state: directory
      mode: 0700

- name: Pushes user's rsa key to root's vagrant box. (It is ok if this Task fails)
  copy:
      src: "~/.ssh/id_rsa.pub"
      dest: "/root/.ssh/authorized_keys"
      owner: root
      mode: 0600
  register: rsa
  ignore_errors: yes

- name: Pushes user's dsa key to root's vagrant box.
  copy:
      src: "~/.ssh/id_dsa.pub"
      dest: "/root/.ssh/authorized_keys"
      owner: root
      mode: 0600
  when: rsa|failed
