---
  - name: Add repo for Apache 2.4
    get_url:
      url: "http://repos.fedorapeople.org/repos/jkaluza/httpd24/epel-httpd24.repo"
      dest: "/etc/yum.repos.d/epel-httpd24.repo"
      mode: 0644

  # httpd24-httpd-devel gives us apxs, which is used to build apache modules.
  # We need it to build mod_wsgi by hand.
  - name:  Install necessary packages
    yum:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - httpd24
      - httpd24-httpd-devel
      #- openssl

  - name: Configure Apache to listen on 80
    lineinfile:
      dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
      regexp: "^Listen "
      line: "Listen 80"
      state: present
    notify:
      - restart httpd24-httpd

  - name: Name Apache vhost for :80
    lineinfile:
      dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
      regexp: "^NameVirtualHost "
      line: "NameVirtualHost *:80"
      state: present
    notify:
      - restart httpd24-httpd

  # TODO: Support SSL properly. See also settings.local_post.php
  #
  # mod_ssl will take care of listening on 443
  # - name: Name Apache vhost for :443
  #   lineinfile:
  #     dest: "/opt/rh/httpd24/root/etc/httpd/conf/httpd.conf"
  #     line: "NameVirtualHost *:443"
  #     state: present
  #   notify:
  #    - restart httpd24-httpd
  #
  # - name: Create directory for SSL cert
  #   file: path=/opt/rh/httpd24/root/etc/httpd/ssl state=directory
  #
  # - name: Generate SSL cert
  #   command: "openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj '/C=US/ST=Colorado/L=Boulder/O=UComm/CN=express.local' -keyout /opt/rh/httpd24/root/etc/httpd/ssl/apache.key -out /opt/rh/httpd24/root/etc/httpd/ssl/apache.crt"
  #   args:
  #     creates: /opt/rh/httpd24/root/etc/httpd/ssl/apache.crt

  - name: Update user apache groups
    user:
        name: "apache"
        groups: "osr_web_deploy"
        append: yes

  - name: Update user osr_web_deploy groups
    user:
        name: "osr_web_deploy"
        groups: "apache"
        append: yes

  - name: Apache should own it's logs
    file:
      path:  /opt/rh/httpd24/root/var/log/httpd
      owner: apache
      group: apache

  - name: Create symlinks to allow mod_wsgi to compile
    become: yes
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    with_items:
      - { src: "/opt/rh/httpd24/root/usr/lib64/httpd", dest: "/httpd"}
      - { src: "/opt/rh/httpd24/root/usr/lib64/apr-1", dest: "/apr-1"}

  - name: Ensure Apache 2.4 (httpd24-httpd) is started and enabled on boot.
    service:
        name: httpd24-httpd
        state: started
        enabled: yes
