---
- hosts: 127.0.0.1

  vars_prompt:
    - name: "key_file"
      prompt: "Enter the path ssh key that you use to connect to GitHub. Leave blank for"
      private: no
      default: "~/.ssh/id_rsa.pub"

  connection: local

  tasks:
    - name: Create initial directory structure
      file: path={{ item }} state=directory mode=0775
      with_items:
        - "~/express_local/data/code"

    - name: Clone Varnish VCL for Varnish 3
      git:
        repo: "git@github.com:CuBoulder/varnish.git"
        dest: "~/express_local/data/code/varnish-3"
        version: "master"
        accept_hostkey: yes
        key_file: "{{ key_file }}"

    - name: Clone Varnish VCL for Varnish 4
      git:
        repo: "git@github.com:johnquest/varnish.git"
        dest: "~/express_local/data/code/varnish"
        version: "feature/varnish4"
        accept_hostkey: yes
        key_file: "{{ key_file }}"

    - name: Clone Inventory
      git:
        repo: "git@github.com:CuBoulder/atlas.git"
        dest: "~/express_local/data/code/atlas"
        version: "master"
        accept_hostkey: yes
        key_file: "{{ key_file }}"
