---
  # This playbook will be run on webservers for Express.
  # Drush includes the Composer install, so needs to be before Behat.
  - hosts: web
    become: yes

    # Pick which configuration files we want to swap in
    vars:
        express_code_varnish: true
        express_code_elk: false
        express_code_logstash: false
        express_code_logstash_shipper: true
    roles:
        - {role: ssh_keys, key_set: 'user' }
        - {role: server_base }
        - {role: apache }
        - {role: php }
        - {role: mysql }
        - {role: varnish }
        - {role: apc }
        - {role: memcache }
        - {role: xdebug }
        - {role: rvm }
        - {role: drush }
        - {role: behat }
        #- {role: logstash }
        - {role: express_code }
        - {role: logging }
        - {role: ssh_keys, key_set: 'dplagnt_dest' }
