---
  # This playbook will be run on the logging server for Express.
  - hosts: logging
    become: yes
    # Copy in the ELK configuration
    vars:
        express_code_varnish: false
        express_code_elk: true
        express_code_logstash: true
        express_code_logstash_shipper: false
    roles:
        - {role: ssh_keys}
        - {role: server_base }
        - {role: elasticsearch }
        - {role: logstash }
        - {role: kibana }
        - {role: redis }
        - {role: express_code }
